### ISSUE TITLE
Pivot char algorithm should handle parens

### ISSUE THREAD

**Issue by mnojima-visa** [cnojima/vscode-extension-readable-indent#13]
**Describe the bug**
When indenting GraphQL queries with args, indentation selects
incorrect char for indent pivot.

**To Reproduce**
1. Apply RI function to GraphQL query (see attached)
2. see that unexpected char is used as pivot.

**Expected behavior**
Algorithm to find correct pivot char needs to include parens.

```
type Mutation {
  bookTrips(launchIds: [ID]!): TripUpdateResponse!
  cancelTrip(launchId: ID!): TripUpdateResponse!
  login(email: String): String
}
```
becomes
```
type Mutation {
  bookTrips(launchIds : [ID]!): TripUpdateResponse!
  cancelTrip(launchId : ID!): TripUpdateResponse!
  login(email         : String): String
}
```

**Comment by cnojima** [comment]
Fixed in v1.0.1
