### ISSUE TITLE
Readible indent Julia language issue with ::

### ISSUE THREAD

**Issue by AquaPore** [cnojima/vscode-extension-readable-indent#44]
Hi,

This is one of my favorit visual studio code snippet.

This is just a small issue in Julia language when using the  Readible indent which makes a small space between : : 

Here is when I use your amazing snippet:

`Base.@kwdef mutable struct OPTIM
         Param_Name            **: :** Vector{String}
         ParamOpt_Min          **: :** Vector{Float64}
   	end`

It makes an indiserable space between the : [space] : , do you think it is possible to remove the space. 

Many thanks for any help you may provide,
Joseph

**Comment by mnojima-visa** [comment]
Glad you're still using this!  Work WAF won't let me clone/install deps, but i'll see if i can get something together later tonight.

**Comment by cnojima** [comment]
v1.3.1 published.  hope this helps you!

**Comment by AquaPore** [comment]
Dear Cnojima,

A really great thanks, I tested your code and I would like to confirm that you sucessfully fixed the issue of :: by using  Julia code. Now the code looks very tiedy.

Are there any more usefull extensions in VSC which you developped/recommend?

Thanks for your kind help,
Joseph
